language: node_js

node_js:
  - stable

install:
  - npm install
  - npm install -g mocha
  - npm install -g nyc

script:
  - cp example_config.toml config.toml
  - npm test
after_success: npm run coverage