language: node_js

node_js:
  - stable

install:
  - npm install
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g typescript
  - npm install -g coveralls
  - mkdir logs
  - touch logs/dev.log
  - cp test/testconfig.toml config/config.toml
  - npm run tsc

script:
  - npm run coverage

notifications:
  webhooks: https://chatbot-travis-webhook.herokuapp.com/webhook