language: node_js

node_js:
  - stable

install:
  - npm install
  - npm install -g mocha
  - npm install -g istanbul

script:
  - mkdir logs
  - touch logs/dev.log
  - cp example_config.toml config.toml
  - npm run coverage